services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "9000:8080"
    environment:
      - RUN_ID=21cf301e4e7f459bae86218626159897
      - EXPERIMENT_NUMBER=1
    volumes:
      - "${HOME}/.aws/credentials:/root/.aws/credentials:ro"
